 
include $(TOP_DIR)/Make.common
TrilinosSrcDir:=$(PWD)/trilinos-11.4.1-Source
TrilinosBuildDir:=$(PWD)/trilinos-build
TrilinosInstallDir:=$(TRILINOS_DIR)


DisTar:=Trilinos-trilinos-release-11-4-1.tar.gz

all: $(TrilinosInstallDir)
 
trilinos-11.4.1-Source.tar.gz:
	#old: wget http://trilinos.sandia.gov/download/files/trilinos-11.4.1-Source.tar.gz
ifeq ( "$(DisTar)","") 
else
	rm $(DisTar) 
endif

	wget https://gitlab.osti.gov/jmwille/Trilinos/-/archive/trilinos-release-11-4-1/$(DisTar)

$(TrilinosSrcDir): trilinos-11.4.1-Source.tar.gz
    #old: tar -xvf trilinos-11.4.1-Source.tar.gz
	tar -xvf $(DisTar) --transform s/Trilinos-trilinos-release-11-4-1/trilinos-11.4.1-Source/
	sed -i '13s/elasticity.dat//' ./trilinos-11.4.1-Source/packages/ml/test/MultiLevelPreconditioner_Sys/CMakeLists.txt; \
	sed -i '107s/return stream/return true/' ./trilinos-11.4.1-Source/packages/nox/src-lapack/NOX_LAPACK_Matrix.H

$(TrilinosBuildDir)/Makefile: $(TrilinosSrcDir) do-configure.sh
	mkdir -p $(TrilinosBuildDir); \
	cp do-configure.sh $(TrilinosBuildDir)/do-configure.sh; \
	cd $(TrilinosBuildDir); \
	TRILINOS_HOME=$(TrilinosSrcDir) TRILINOS_INSTALL=$(TrilinosInstallDir) sh ./do-configure.sh 

$(TrilinosInstallDir): $(TrilinosBuildDir)/Makefile
	cd $(TrilinosBuildDir); \
	gmake -j 8 
	cd $(TrilinosBuildDir); \
	gmake -j 48 install
	
realclean:
	rm -rf $(TrilinosBuildDir)
	rm -rf $(TrilinosSrcDir)
	rm -f *.tar.gz
